name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Build, Typecheck, Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ".nvmrc"

      - name: Setup Yarn
        run: |
          corepack enable
          corepack prepare yarn@4.5.3 --activate

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build Packages
        run: yarn build:packages

      - name: Typecheck
        run: yarn typecheck

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test:coverage
